version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - gochecksumtype
    - goconst
    - iface
    - ireturn
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - predeclared
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wrapcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    ireturn:
      allow:
        - error
        - empty
        - anon
        - stdlib
        - generic
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
